# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

"""
    I do not guarantee the correctness of this commentary, thus it is based only on my personal analysis of the code.

    This file holds the definitions of the gui elements, and the name of the function called when the OK button is clicked.

"""

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Title', kernelModule='loadNanoindenterTest', kernelFunction='loadmaterials', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgComboBox(name='ComboBox_1', p='DialogBox', text='Text:', keyword='indenter', default='', comboType='STANDARD', repository='', rootText='', rootKeyword='None', layout='')
RsgListItem(p='ComboBox_1', text='spherical')
RsgListItem(p='ComboBox_1', text='Vickers')
RsgListItem(p='ComboBox_1', text='Berkovich')
dialogBox.show()