# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *

from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='test', kernelModule='testRSGPluginKernelScript',
                      kernelFunction='loadmaterials()', includeApplyBtn=False, includeSeparator=True, okBtnText='OK',
                      applyBtnText='Apply', execDir=thisDir)
RsgLabel(p='DialogBox', text='Label', useBoldFont=False)
RsgIcon(p='DialogBox', fileName=r'icon.png')
RsgRadioButton(p='DialogBox', text='Text', keyword='DialogBox', default=False)
RsgCheckButton(p='DialogBox', text='Text', keyword='keyword01', default=True)
RsgCheckButton(p='DialogBox', text='Text', keyword='keyword02', default=True)
dialogBox.show()